# pytest.ini
[pytest]
asyncio_mode = off
log_cli = true
log_cli_level = INFO
addopts = -v --alluredir=reports/allure-results
testpath =
    api/tests
    ui/tests
markers =
    api
    ui
    smoke: mark test as part of smoke suite
    regression: mark test as part of regression suite
    sanity: mark test as part of sanity suite
